services:

  devcontainer:
    build:
      target: dev
    environment:
      - UV_PUBLISH_TOKEN
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

volumes:
  command-history-volume:


